name: linksoap
description: Launder your clipboard.
publish_to: "none"

version: 0.1.1-beta+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  system_tray: ^2.0.3
  window_manager: ^0.5.1
  windows_single_instance: ^1.0.1
  logging: ^1.3.0
  shared_preferences: ^2.3.4
  flutter_slidable: ^3.1.1
  url_launcher: ^6.3.1
  diff_match_patch: ^0.4.1
  ansicolor: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/icon.png
    - assets/icon.ico
    - assets/bg.png
    - assets/fg.png

# dart run flutter_launcher_icons
flutter_launcher_icons:
  image_path: "assets/icon.png"
  android:
    adaptive_icon_background: "assets/bg.png"
    adaptive_icon_foreground: "assets/fg.png"
  windows:
    generate: true
    image_path: "assets/icon.ico"
